image: node:8.9.3

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - test
  - build
  - develop
  - production

test:
  stage: test
  script:
    - npm install
    - npm test
  services:
    - mongo
  variables:
    MONGODB_URI: 'mongodb://mongo/webprojects-test'
    NODE_ENV: 'test'

build:
  stage: build
  script:
    - npm install -g gulp
    - npm install
    - gulp build
  artifacts:
    expire_in: 1 week
    paths:
      - dist/

develop:
  type: deploy
  stage: develop
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - cd dist
    - dpl --provider=heroku --app=web-projects-winter-2018-devel --api-key=$HEROKU_API_KEY
  only:
    - develop

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - ls
    - cd dist
    - ls
    - dpl --provider=heroku --app=web-projects-winter-2018-prod --api-key=$HEROKU_API_KEY
  only:
    - master
